package com.findbest.findbest.enums.store;

public enum LocalStoreEnum {
//    MAXI_AZ, -- Cannot fetched by JSOUP
// BAKENROLL_AZ, -- 500 INTERNAL SERVER ERROR
// FLOSTORE_AZ, -- 404 NOT FOUND
// ITICKET_AZ, -- REDUNDANT
// SANTRAL_AZ -- Not render
// SABAHFC_AZ, -- PRIVATE SITE
// NEXT_COM_AZ, -- NOT LOCAL (AZERBAIJAN)
// AZEXPORT_AZ -- RENDDER PROBLEM
// LINEX_AZ -- Does not work

    KONTAKT_AZ,
    BAKUELECTRONICS_AZ,
    UMICO_AZ,
    BAZARSTORE_AZ,
    AZ_ORIFLAME_COM,
    ALININO_AZ,
    UNIMALL_AZ,
    COMPSTORE_AZ,
    MGSTORE_AZ,
    KITABEVIM_AZ,
    ALMALI_AZ,
    NEPTUN_AZ,
    OMID_AZ,
    BAKUBOOKCENTER_AZ,
    EMBAWOOD_AZ,
    YVESROCHER_AZ,
    UNITEDSPORT_AZ,
    BODYCARE_AZ,
    GOSPORT_AZ,
    LIFE_SPORT_AZ,
    SAATSTORE_AZ,
    NOVELLA_AZ,
    EMSAN_COM_AZ,
    EVIMIZSTORE_AZ,
    BIOTUS_AZ,
    MADEYRA_COM,
    DECORIA_AZ,
    LIBRAFF_AZ,
    OPTIMAL_AZ,
    TEKERSTORE_AZ,
    PROTEINSHOP_AZ,
    SUPERFON_AZ,
    SARALTECH_STORE,
    AXCA_AZ,
    TOPBRANDS_AZ,
    ALIN_AZ,
    AYBAX_COM,
    TIMSPORT_AZ,
    ARIZON_AZ,
    BUTALI_AZ,
    DINO_AZ,
    VOLKSSPORT_AZ,
    USEL_AZ,
    REALBUY_AZ,
    OFISAIT_AZ,
    HAMISIBURADA_AZ,
    SUPREMEBEL_AZ,
    ERAELECTRONICS_AZ,
    ASANGUL_COM,
    ANTARIS_AZ,
    GALLERY_AZ,
    BONPOPPY_AZ,
    YUMROO_AZ,
    CINARYAYIMLARI_COM,
    ALSEVIN_AZ,
    DUAL_AZ,


    LEKAL_AZ,

}

